### ISSUE TITLE
formatting ?  

### ISSUE THREAD

**Issue by omgbox** [solaris7x/peer_river#2]
what is the right formatting

http://127.0.0.1:3000/getfile?torrent=magnet ?

i cant figure it out :(

**Comment by solaris7x** [comment]
The app has 2 endpoints , 
1. To list the files for given magnet URI
   `localhost:port/listfiles?magnetURI=magnet-link` 
 eg. `http://localhost:3000/listfiles?magnetURI=magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel`

2. To get any 1 specific file from the given torrent magnet
 `localhost:port/lgetfile?magnetURI=magnet-link&fileIndex=0`
 The default fileIndex is 0 , you can find the index of specific a file from /listfiles endpoint 
 eg. `http://localhost:3000/getfile?magnetURI=magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&fileIndex=2`
 

Btw I wrote this app for simple experimentation , as such dependency versions might be outdated.
Also the torrent size cannot be larger than storage space of the machine you run it on

**Comment by omgbox** [comment]
very cool, its working good, how to spin another process to accept another torrent to stream. its only allowing me to watch 1 torrent , i open second terminal and try to submit new stream but i get this error

`(node:6352) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added to [Torrent]. Use emitter.setMaxListeners() to increase limit
Taking too long
Destroyed client`

**Comment by solaris7x** [comment]
You can do multiple request to 1 app instance normally. As I made this app to experiment with webtorrent , This aint production ready. 

The warning you are posted is from nodejs safety check and is directly inherited from webtorrent package. You can refer to https://github.com/webtorrent/webtorrent/issues/889

As the warning is from dependency webtorrent package , I can't do anything about it.

**Comment by omgbox** [comment]
understood many thanks.
